services:
  - type: web
    name: mv-traders-backend
    runtime: node
    rootDir: backend-example
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYTM_MID
        sync: false
      - key: PAYTM_MERCHANT_KEY
        sync: false
      - key: PAYTM_WEBSITE
        value: DEFAULT
      - key: PAYTM_INDUSTRY_TYPE
        value: Retail
      - key: PAYTM_CHANNEL_ID
        value: WEB
      - key: PAYTM_ENV
        value: production
      - key: PAYTM_CALLBACK_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
